---
tilesets:     
  - id: mountain1
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/mountain1.png"
...