---
tilesets:     
  - id: volcano2
    biomes:
      - types: [grass, ice, desert, volcano]
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/volcano2.png"
...