---
tilesets:     
  - id: mountain2
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedNoHor
        iconSprite: ":img:ui/terrains/icons/mountain2.png"
...