---
tilesets:     
  - id: ocean0
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedNoHor
        iconSprite: ":img:ui/terrains/icons/ocean0.png"
...