---
tilesets:     
  - id: mountain0
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedNoHor
        iconSprite: ":img:ui/terrains/icons/mountain0.png"
...