---
tilesets:     
  - id: beach0
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedNoHor
        iconSprite: ":img:ui/terrains/icons/beach0.png"
...