---
tilesets:     
  - id: bridge2
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedNoHor
        iconSprite: ":img:ui/terrains/icons/bridge2.png"
...