---
tilesets:     
  - id: ocean1
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedTerrain
        iconSprite: ":img:ui/terrains/icons/ocean1.png"
...