---
tilesets:     
  - id: forest1
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/forest1.png"
...