---
tilesets:     
  - id: carpet0
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedTerrain
        iconSprite: ":img:ui/terrains/icons/carpet0.png"
...