---
tilesets:     
  - id: forest2
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedTerrain
        iconSprite: ":img:ui/terrains/icons/forest2.png"
...