---
tilesets:     
  - id: ocean2
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedTerrain
        iconSprite: ":img:ui/terrains/icons/ocean2.png"
...