---
tilesets:     
  - id: plains1
    biomes:
      - types: [grass, ice, desert, volcano]
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/plains1.png"
...