---
tilesets:     
  - id: river1
    biomes:
      - types: [grass, ice, desert, volcano]
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/river1.png"
...