---
tilesets:     
  - id: volcano1
    biomes:
      - types: [grass, ice, desert, volcano]
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/volcano1.png"
...