---
tilesets:     
  - id: wall0
    biomes:
      - types: [grass, ice, desert, volcano]
        iconSpriteSheet: ui_UniExpandedRandomBridge
        iconSprite: ":img:ui/terrains/icons/wall0.png"
...