---
tilesets:     
  - id: carpet1
    biomes:
      - types: [grass, ice, desert, volcano]     
        iconSpriteSheet: ui_UniExpandedTerrain
        iconSprite: ":img:ui/terrains/icons/carpet1.png"
...